In [204]:
import pandas as pd
import numpy as np

In [205]:
basic_stats = pd.read_csv(r'../data/wnba_players_basic_stats.csv')
basic_stats.drop(columns=['Unnamed: 0'], inplace=True)
print(basic_stats.shape)
basic_stats.head()

(4691, 25)

,Season,Player,G,MP,GS,FG,FGA,FG%,3P,3PA,...,FTA,FT%,ORB,TRB,AST,STL,BLK,TOV,PF,PTS
0,1997,Anita Maxwell,9,63,0,8,25,0.320,0,0,...,8,0.375,2,12,8,4,0,6,5,19
1,1997,Tammi Reiss,28,831,26,72,231,0.312,30,101,...,55,0.764,29,77,87,23,2,61,57,216
2,1997,Catarina Pollini,13,94,0,8,22,0.364,0,0,...,12,0.500,3,12,5,4,1,8,21,22
3,1997,Bridget Pettis,28,842,28,107,320,0.334,41,134,...,108,0.898,36,107,78,49,11,82,57,352
4,1997,Kim Perrot,28,692,24,59,162,0.364,28,99,...,37,0.405,18,75,88,69,2,65,53,161

In [206]:
advanced_stats = pd.read_csv(r'../data/wnba_advanced_players_stats.csv')
advanced_stats.drop(columns=['Unnamed: 0'], inplace=True)
print(advanced_stats.shape)
advanced_stats.head()

(4691, 20)

,Season,Player,PER,TS%,eFG%,3PAr,FTr,ORB%,TRB%,AST%,STL%,BLK%,TOV%,USG%,ORtg,DRtg,OWS,DWS,WS,WS/40
0,1997,Anita Maxwell,10.6,0.333,0.320,0.000,0.320,4.3,12.3,24.8,3.5,0.0,17.4,25.6,72.0,89.0,-0.2,0.1,-0.1,-0.036
1,1997,Tammi Reiss,9.6,0.423,0.377,0.437,0.238,3.9,5.3,20.8,1.5,0.2,19.3,17.0,87.0,105.0,0.2,-0.7,-0.5,-0.024
2,1997,Catarina Pollini,4.6,0.403,0.364,0.000,0.545,4.1,8.4,10.0,2.4,0.9,22.7,17.6,77.0,92.0,-0.1,0.1,0.0,0.005
3,1997,Bridget Pettis,17.0,0.479,0.398,0.419,0.338,5.0,7.8,20.4,3.1,1.1,18.2,24.0,94.0,88.0,1.5,1.7,3.2,0.151
4,1997,Kim Perrot,14.1,0.452,0.451,0.611,0.228,3.4,7.2,23.8,5.6,0.2,26.7,16.5,87.0,87.0,0.2,1.5,1.7,0.098

In [207]:
mvp_votes = pd.read_csv(r'../data/wnba_mvp_votes.csv')
mvp_votes.drop(columns=['Unnamed: 0'], inplace=True)
print(mvp_votes.shape)
mvp_votes.tail()

(411, 21)

,Season,Rank,Player,Age,Tm,First,Pts Won,Pts Max,award_share,G,...,PTS,TRB,AST,STL,BLK,FG%,3P%,FT%,WS,WS/48
406,2025,9T,Veronica Burton,24,GSV,0.0,1.0,720,0.001,44,...,11.9,4.4,6.0,1.1,0.6,0.387,0.345,0.878,6.4,0.238
407,2025,9T,Dearica Hamby,31,LAS,0.0,1.0,720,0.001,44,...,18.4,7.9,3.3,1.6,0.5,0.572,0.278,0.627,5.6,0.195
408,2025,9T,Rhyne Howard,24,ATL,0.0,1.0,720,0.001,33,...,17.5,4.5,4.6,1.5,0.8,0.375,0.322,0.856,5.1,0.212
409,2025,9T,Rickea Jackson,23,LAS,0.0,1.0,720,0.001,38,...,14.7,3.2,1.7,0.6,0.4,0.424,0.348,0.847,0.3,0.011
410,2025,9T,Breanna Stewart,30,NYL,0.0,1.0,720,0.001,31,...,18.3,6.5,3.5,1.4,1.4,0.461,0.241,0.837,4.9,0.246

In [208]:
players_pm = pd.read_csv(r'../data/wnba_players_plus_minus.csv')
players_pm.drop(columns=['Unnamed: 0'], inplace=True)
print(players_pm.shape)
players_pm.head()

(4691, 3)

   Season             Player  PLUS_MINUS
0    1997   Adrienne Johnson          29
1    1997  Andrea Congreaves          50
2    1997     Andrea Stinson          54
3    1997      Anita Maxwell          -5
4    1997     Bridget Pettis          91

In [209]:
mvps = pd.read_csv(r'../data/wnba_mvps.csv')
mvps.drop(columns=['Unnamed: 0'], inplace=True)
mvps.head()

,Year,Player,Voting,Tm,G,MP,PTS,TRB,AST,STL,BLK,FG%,3P%,FT%,WS,WS/48
0,2025,A'ja Wilson,NaN,LVA,40,31.2,23.4,10.2,3.1,1.6,2.3,0.505,0.424,0.855,9.5,0.365
1,2024,A'ja Wilson,NaN,LVA,38,34.4,26.9,11.9,2.3,1.8,2.6,0.518,0.317,0.844,10.9,0.399
2,2023,Breanna Stewart,NaN,NYL,40,34.1,23.0,9.3,3.8,1.5,1.6,0.465,0.355,0.851,10.3,0.362
3,2022,A'ja Wilson,NaN,LVA,36,30.0,19.5,9.4,2.1,1.4,1.9,0.501,0.373,0.813,6.5,0.289
4,2021,Jonquel Jones,NaN,CON,27,31.7,19.4,11.2,2.8,1.3,1.3,0.515,0.362,0.802,6.6,0.369

In [210]:
mvps_dict = mvps[['Year', 'Player']].set_index('Year').to_dict()['Player']
mvps_dict

{2025: "A'ja Wilson",
 2024: "A'ja Wilson",
 2023: 'Breanna Stewart',
 2022: "A'ja Wilson",
 2021: 'Jonquel Jones',
 2020: "A'ja Wilson",
 2019: 'Elena Delle Donne',
 2018: 'Breanna Stewart',
 2017: 'Sylvia Fowles',
 2016: 'Nneka Ogwumike',
 2015: 'Elena Delle Donne',
 2014: 'Maya Moore',
 2013: 'Candace Parker',
 2012: 'Tina Charles',
 2011: 'Tamika Catchings',
 2010: 'Lauren Jackson',
 2009: 'Diana Taurasi',
 2008: 'Candace Parker',
 2007: 'Lauren Jackson',
 2006: 'Lisa Leslie',
 2005: 'Sheryl Swoopes',
 2004: 'Lisa Leslie',
 2003: 'Lauren Jackson',
 2002: 'Sheryl Swoopes',
 2001: 'Lisa Leslie',
 2000: 'Sheryl Swoopes',
 1999: 'Yolanda Griffith',
 1998: 'Cynthia Cooper',
 1997: 'Cynthia Cooper'}

Due to NBA api and Basketball Refrence spelling or using different letters for these players

In [ ]:
# name mapping after carefull checking
name_mapping_corrected = {
    'Margo Clark': 'Margold Clark',
    'Pam McGee': 'Pamela McGee',
    'Raegan Scott': 'Raegan Pebley',
    'Trena Trice-Hill': 'Trena Trice',
    'Alessandra Santos de Olive': 'Alessandra Santos de Oliveira',
    'Angela Hamblin':'Angie Hamblin',
    'Annie Burgess': 'Annie La Fleur',
    'Heather Quella': 'Heather Burge',
    'Leila de Souza Sobral': 'Leila Sobral',
    'Sandra VanEmbricqs': 'Sandra Van Embricqs',
    'Merlelynn Lang-Harris': 'MerleLynn Lange-Harris',
    'Val Whiting': 'Val Whiting-Raymond',
    'Towana Alhaleem':'Tawona Alhaleem',
    'TaKeisha Lewis':'Takeisha Lewis',
    'Joy Holmes': 'Joy Holmes-Harris',
    'Sun Min Jung':'Jung Sun-Min',
    'Vedrana Grgin Fonseca': 'Vedrana Grgin-Fonseca',
    'Adriana Moises Pinto': 'Adriana Moises',
    'LaQuanda Quick': 'LaQuanda Barksdale',
    'Zuzana Klimesova': 'Zuzi Klimesova',
    'Catrina Frierson':'Trina Frierson',
    'Miao Li jie': 'Miao Lijie',
    'Sui Fei Fei': 'Sui Feifei',
    'Tamika Raymond':'Tamika Williams',
    'Tenae Davis-Cain':'Tanae Davis-Cain',
    'Susan King-Borchardt': 'Susan King Borchardt',
    'Dalivorka Vilipic': 'Daliborka Vilipic',
    'Tiffany Jackson': 'Tiffany Jackson-Jones',
    'Sharnee Zoll-Norman': 'Sharnee Zoll',
    'Jayne Appel Marinelli': 'Jayne Appel-Marinelli',
    'Asia (AD) Durr':'AD Durr',
    'Felicia Chester-Wootton': 'Felicia Chester',
    'Aneika Morello': 'Aneika Henry-Morello',
    'Briana Butler': 'Briana Gilbreath-Butler',
    'Amanda Zahui B': 'Amanda Zahui B.',
    'Brittany Boyd-Jones': 'Brittany Boyd',
    'Evgeniia Belyakova': 'Evgeniya Belyakova',
    'Marie Gülich': 'Marie Gulich',
    'Dorka Juhasz': 'Dorka Juhász',
    'Sika Kone': 'Sika Koné',
    'Lou Lopez Senechal': 'Lou Lopez Sénéchal',
    'Nika Muhl': 'Nika Mühl',
    'Leila Lacan':'Leïla Lacan',
    'Anastasiia Olairi Kosu': 'Anastasiia Kosu',
    'Janelle Salaun': 'Janelle Salaün',
    'Olivia Epoupa':'Olivia Époupa',
    'Luisa Geiselsoder': 'Luisa Geiselsöder',
    'Mamignan Toure': 'Mamignan Touré',
    'Te-Hina Paopao': 'Te-Hina PaoPao'
}
players_pm['Player'] = players_pm['Player'].replace(name_mapping_corrected)

In [212]:
final_df = basic_stats.merge(advanced_stats, on=['Season','Player']).merge(players_pm, on=['Season', 'Player'], how='left').merge(mvp_votes[['Season', 'Player', 'award_share']], on=['Season', 'Player'], how='left')
final_df

,Season,Player,G,MP,GS,FG,FGA,FG%,3P,3PA,...,TOV%,USG%,ORtg,DRtg,OWS,DWS,WS,WS/40,PLUS_MINUS,award_share
0,1997,Anita Maxwell,9,63,0,8,25,0.320,0,0,...,17.4,25.6,72.0,89.0,-0.2,0.1,-0.1,-0.036,-5,NaN
1,1997,Tammi Reiss,28,831,26,72,231,0.312,30,101,...,19.3,17.0,87.0,105.0,0.2,-0.7,-0.5,-0.024,-288,NaN
2,1997,Catarina Pollini,13,94,0,8,22,0.364,0,0,...,22.7,17.6,77.0,92.0,-0.1,0.1,0.0,0.005,19,NaN
3,1997,Bridget Pettis,28,842,28,107,320,0.334,41,134,...,18.2,24.0,94.0,88.0,1.5,1.7,3.2,0.151,91,NaN
4,1997,Kim Perrot,28,692,24,59,162,0.364,28,99,...,26.7,16.5,87.0,87.0,0.2,1.5,1.7,0.098,155,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4686,2025,Brittney Sykes,39,1194,38,174,457,0.381,31,102,...,15.0,25.1,97.0,106.0,0.0,1.4,1.4,0.046,6,NaN
4687,2025,Stephanie Talbot,38,541,10,39,104,0.375,16,56,...,25.6,13.4,95.0,103.0,-0.1,0.8,0.7,0.054,-28,NaN
4688,2025,Sevgi Uzun,25,439,3,31,95,0.326,5,30,...,29.6,14.8,74.0,113.0,-1.2,0.0,-1.2,-0.105,-52,NaN
4689,2025,Julie Vanloo,35,449,2,33,111,0.297,25,92,...,29.8,16.7,79.0,111.0,-1.0,0.2,-0.9,-0.078,-127,NaN
4690,2025,Li Yueru,31,519,12,62,153,0.405,20,55,...,14.6,17.3,108.0,111.0,0.7,0.2,0.9,0.071,-25,NaN

In [213]:
final_df['is_mvp'] = np.array(1 if mvps_dict[row['Season']] == row['Player'] else 0 for _ , row in final_df[['Season','Player']].iterrows())
final_df[final_df['is_mvp'] == 1]

,Season,Player,G,MP,GS,FG,FGA,FG%,3P,3PA,...,USG%,ORtg,DRtg,OWS,DWS,WS,WS/40,PLUS_MINUS,award_share,is_mvp
63,1997,Cynthia Cooper,28,982,28,191,406,0.470,67,162,...,28.7,119.0,92.0,8.1,1.3,9.4,0.385,176,1.000,1
131,1998,Cynthia Cooper,30,1051,30,203,455,0.446,64,160,...,29.9,119.0,91.0,8.1,1.9,10.0,0.382,358,0.947,1
270,1999,Yolanda Griffith,29,979,29,200,370,0.541,0,1,...,24.4,117.0,87.0,5.3,2.8,8.1,0.330,194,0.778,1
543,2000,Sheryl Swoopes,31,1090,31,245,484,0.506,34,91,...,28.6,116.0,85.0,6.3,3.6,9.8,0.361,399,0.850,1
672,2001,Lisa Leslie,31,1033,31,221,467,0.473,22,60,...,29.8,108.0,90.0,4.8,2.2,7.0,0.272,309,0.938,1
950,2002,Sheryl Swoopes,32,1154,32,221,509,0.434,23,80,...,29.7,103.0,85.0,3.3,3.8,7.1,0.247,188,0.803,1
1063,2003,Lauren Jackson,33,1109,33,254,526,0.483,39,123,...,30.2,117.0,91.0,6.7,2.5,9.2,0.333,120,0.752,1
1244,2004,Lisa Leslie,34,1150,34,223,451,0.494,6,22,...,27.1,102.0,85.0,3.0,3.7,6.8,0.236,123,0.885,1
1461,2005,Sheryl Swoopes,33,1225,33,217,486,0.447,27,75,...,27.0,111.0,97.0,5.6,1.6,7.1,0.233,60,0.654,1
1582,2006,Lisa Leslie,34,1048,34,257,503,0.511,8,20,...,31.4,104.0,88.0,3.3,3.0,6.4,0.243,164,0.924,1
1740,2007,Lauren Jackson,31,1020,31,258,497,0.519,49,122,...,28.0,128.0,96.0,7.9,1.6,9.5,0.373,244,0.985,1
1971,2008,Candace Parker,33,1109,33,231,442,0.523,11,26,...,24.6,113.0,89.0,4.7,3.0,7.7,0.278,115,0.923,1
2178,2009,Diana Taurasi,31,976,31,200,434,0.461,79,194,...,25.4,117.0,103.0,4.7,0.7,5.4,0.222,152,0.828,1
2263,2010,Lauren Jackson,32,993,32,220,476,0.462,54,156,...,27.3,126.0,96.0,6.1,2.2,8.3,0.333,295,0.873,1
2373,2011,Tamika Catchings,33,1040,33,168,384,0.438,32,92,...,23.7,114.0,94.0,4.1,2.3,6.5,0.248,180,0.749,1
2519,2012,Tina Charles,33,1096,33,250,501,0.499,1,5,...,25.1,109.0,97.0,3.5,1.9,5.5,0.200,138,0.885,1
2735,2013,Candace Parker,31,889,31,208,422,0.493,9,35,...,28.9,111.0,89.0,4.1,2.5,6.5,0.295,196,0.669,1
2887,2014,Maya Moore,34,1181,34,295,613,0.481,62,185,...,30.1,116.0,96.0,6.2,2.2,8.3,0.283,230,0.976,1
2983,2015,Elena Delle Donne,31,1032,31,238,517,0.460,42,134,...,27.9,126.0,97.0,7.3,1.6,8.9,0.346,211,0.987,1
3202,2016,Nneka Ogwumike,33,1043,33,244,367,0.665,16,26,...,23.0,135.0,95.0,7.0,2.7,9.6,0.370,252,0.928,1
3300,2017,Sylvia Fowles,34,1048,34,254,388,0.655,0,0,...,23.3,127.0,90.0,5.7,3.4,9.2,0.350,334,0.962,1
3530,2018,Breanna Stewart,34,1074,34,270,510,0.529,61,147,...,27.3,122.0,97.0,5.0,2.7,7.7,0.288,275,0.954,1
3609,2019,Elena Delle Donne,31,901,31,220,427,0.515,52,121,...,25.7,130.0,98.0,6.2,1.5,7.7,0.343,371,0.977,1
3864,2020,A'ja Wilson,22,697,22,166,346,0.480,0,0,...,28.2,111.0,94.0,2.1,1.9,4.0,0.230,178,0.974,1
3943,2021,Jonquel Jones,27,856,27,192,373,0.515,42,116,...,27.2,115.0,88.0,3.7,2.9,6.6,0.307,335,0.994,1
4177,2022,A'ja Wilson,36,1080,36,260,519,0.501,31,83,...,27.3,115.0,97.0,4.1,2.4,6.5,0.241,313,0.854,1
4316,2023,Breanna Stewart,40,1365,40,316,680,0.465,82,231,...,27.5,122.0,96.0,7.0,3.3,10.3,0.302,356,0.743,1
4493,2024,A'ja Wilson,38,1308,38,385,743,0.518,19,60,...,32.2,119.0,92.0,7.0,3.8,10.9,0.332,175,1.000,1
4662,2025,A'ja Wilson,40,1247,40,332,658,0.505,25,59,...,31.9,119.0,96.0,6.2,3.3,9.5,0.304,292,0.912,1

In [214]:
final_df['is_mvp'] = final_df['is_mvp'].astype('category')
final_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 4691 entries, 0 to 4690
Data columns (total 46 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Season       4691 non-null   int64
 1   Player       4691 non-null   str
 2   G            4691 non-null   int64
 3   MP           4691 non-null   int64
 4   GS           4691 non-null   int64
 5   FG           4691 non-null   int64
 6   FGA          4691 non-null   int64
 7   FG%          4646 non-null   float64
 8   3P           4691 non-null   int64
 9   3PA          4691 non-null   int64
 10  3P%          3919 non-null   float64
 11  2P           4691 non-null   int64
 12  2PA          4691 non-null   int64
 13  2P%          4623 non-null   float64
 14  FT           4691 non-null   int64
 15  FTA          4691 non-null   int64
 16  FT%          4422 non-null   float64
 17  ORB          4691 non-null   int64
 18  TRB          4691 non-null   int64
 19  AST          4691 non-null   int64
 20  STL          4691 non-null   int64
 21  BLK          4691 non-null   int64
 22  TOV          4691 non-null   int64
 23  PF           4691 non-null   int64
 24  PTS          4691 non-null   int64
 25  PER          4683 non-null   float64
 26  TS%          4653 non-null   float64
 27  eFG%         4646 non-null   float64
 28  3PAr         4646 non-null   float64
 29  FTr          4646 non-null   float64
 30  ORB%         4683 non-null   float64
 31  TRB%         4683 non-null   float64
 32  AST%         4683 non-null   float64
 33  STL%         4683 non-null   float64
 34  BLK%         4683 non-null   float64
 35  TOV%         4664 non-null   float64
 36  USG%         4683 non-null   float64
 37  ORtg         4665 non-null   float64
 38  DRtg         4683 non-null   float64
 39  OWS          4691 non-null   float64
 40  DWS          4691 non-null   float64
 41  WS           4691 non-null   float64
 42  WS/40        4683 non-null   float64
 43  PLUS_MINUS   4691 non-null   int64
 44  award_share  411 non-null    float64
 45  is_mvp       4691 non-null   category
dtypes: category(1), float64(23), int64(21), str(1)
memory usage: 1.6 MB

In [215]:
final_df.isna().sum()

Season            0
Player            0
G                 0
MP                0
GS                0
FG                0
FGA               0
FG%              45
3P                0
3PA               0
3P%             772
2P                0
2PA               0
2P%              68
FT                0
FTA               0
FT%             269
ORB               0
TRB               0
AST               0
STL               0
BLK               0
TOV               0
PF                0
PTS               0
PER               8
TS%              38
eFG%             45
3PAr             45
FTr              45
ORB%              8
TRB%              8
AST%              8
STL%              8
BLK%              8
TOV%             27
USG%              8
ORtg             26
DRtg              8
OWS               0
DWS               0
WS                0
WS/40             8
PLUS_MINUS        0
award_share    4280
is_mvp            0
dtype: int64

In [216]:
final_df.columns[final_df.isna().sum() >0]

Index(['FG%', '3P%', '2P%', 'FT%', 'PER', 'TS%', 'eFG%', '3PAr', 'FTr', 'ORB%',
       'TRB%', 'AST%', 'STL%', 'BLK%', 'TOV%', 'USG%', 'ORtg', 'DRtg', 'WS/40',
       'award_share'],
      dtype='str')

In [217]:
final_df.fillna(0, inplace=True)

,Season,Player,G,MP,GS,FG,FGA,FG%,3P,3PA,...,USG%,ORtg,DRtg,OWS,DWS,WS,WS/40,PLUS_MINUS,award_share,is_mvp
0,1997,Anita Maxwell,9,63,0,8,25,0.320,0,0,...,25.6,72.0,89.0,-0.2,0.1,-0.1,-0.036,-5,0.0,0
1,1997,Tammi Reiss,28,831,26,72,231,0.312,30,101,...,17.0,87.0,105.0,0.2,-0.7,-0.5,-0.024,-288,0.0,0
2,1997,Catarina Pollini,13,94,0,8,22,0.364,0,0,...,17.6,77.0,92.0,-0.1,0.1,0.0,0.005,19,0.0,0
3,1997,Bridget Pettis,28,842,28,107,320,0.334,41,134,...,24.0,94.0,88.0,1.5,1.7,3.2,0.151,91,0.0,0
4,1997,Kim Perrot,28,692,24,59,162,0.364,28,99,...,16.5,87.0,87.0,0.2,1.5,1.7,0.098,155,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4686,2025,Brittney Sykes,39,1194,38,174,457,0.381,31,102,...,25.1,97.0,106.0,0.0,1.4,1.4,0.046,6,0.0,0
4687,2025,Stephanie Talbot,38,541,10,39,104,0.375,16,56,...,13.4,95.0,103.0,-0.1,0.8,0.7,0.054,-28,0.0,0
4688,2025,Sevgi Uzun,25,439,3,31,95,0.326,5,30,...,14.8,74.0,113.0,-1.2,0.0,-1.2,-0.105,-52,0.0,0
4689,2025,Julie Vanloo,35,449,2,33,111,0.297,25,92,...,16.7,79.0,111.0,-1.0,0.2,-0.9,-0.078,-127,0.0,0
4690,2025,Li Yueru,31,519,12,62,153,0.405,20,55,...,17.3,108.0,111.0,0.7,0.2,0.9,0.071,-25,0.0,0

In [219]:
final_df.isna().sum()

Season         0
Player         0
G              0
MP             0
GS             0
FG             0
FGA            0
FG%            0
3P             0
3PA            0
3P%            0
2P             0
2PA            0
2P%            0
FT             0
FTA            0
FT%            0
ORB            0
TRB            0
AST            0
STL            0
BLK            0
TOV            0
PF             0
PTS            0
PER            0
TS%            0
eFG%           0
3PAr           0
FTr            0
ORB%           0
TRB%           0
AST%           0
STL%           0
BLK%           0
TOV%           0
USG%           0
ORtg           0
DRtg           0
OWS            0
DWS            0
WS             0
WS/40          0
PLUS_MINUS     0
award_share    0
is_mvp         0
dtype: int64

In [220]:
final_df.to_csv('../data/wnba_players_data.csv')